name: sql_admin
description: "Admin Application"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  fluttertoast: ^8.2.4
  http: ^1.2.1
  flutter_animate: ^4.5.0
  google_fonts: ^6.2.1
  flutter_zoom_drawer: ^3.2.0
  data_table_2: ^2.5.11
  icons_plus: ^5.0.0
  animated_loading_border: ^0.0.2
  dio: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/config/
    - assets/images/
